### ISSUE TITLE
/etc/smokeping/config seems not to be managed by puppet-smokeping module

### ISSUE THREAD

**Issue by nkarpin** [tobru/puppet-smokeping#25]
Hello,

i am using this module in puppet3 and smokeping is set in standalone mode

i have successfully deployed it on the server using puppet and /etc/smokeping/config file was generated as below and all is working great:

@include /etc/smokeping/config.d/General
@include /etc/smokeping/config.d/Alerts
@include /etc/smokeping/config.d/Database
@include /etc/smokeping/config.d/Presentation
@include /etc/smokeping/config.d/Probes
@include /etc/smokeping/config.d/Slaves
@include /etc/smokeping/config.d/Targets

but when i deleted /etc/smokeping/config i found that it was not recreated when i run puppet,

and i cannot find /etc/smokeping/config in puppet templates or manifests in your module,

can you please look at this and maybe add possibility to manage /etc/smokeping/config using puppet

thank you!

**Comment by jethrocarr** [comment]
hi @nkarpin ,

The /etc/smokeping/config file is provided by the smokeping package itself, rather than by the Puppet module. To recover it, you'll need to re-install the smokeping package.

I'm working on fixing this in the module itself so the module installs *all* required configuration files. Once completed I'll send it through to @tobru as a PR to review. It's a pre-req to have the module run on other distributions such as the EL-family as well.

regards,
Jethro

**Comment by tobru** [comment]
@jethrocarr thanks for your effort! will be happy to review your PR and make a new module release as soons as it's ready
